"use client"
import { supabase } from '../../../lib/supabase'

interface RequestBody {
  table: string,
  id?: number,
  action?: "RESET" | string,
  key?:string
}

export async function callSupabase(functionMethod:"GET"|"PATCH"|"POST", tableName:string, gameId?:number, gameAction?:string, playKey?:string){
  //Pull user's current JWT.
  const { data: { session } } = await supabase.auth.getSession();
  const jwt = session?.access_token;

  //Note that GameIDs are auto-generated by the edge function when using POST.
  const body: RequestBody = {
    table: tableName,
    id:gameId,
    action:gameAction,
    key:playKey,
  }

  //Invoke edge function with user's JWT.
  const { data, error } = await supabase.functions.invoke('postgres-edge', {
    method: functionMethod,
    headers: {
      'Authorization': `Bearer ${jwt}`,
    },
    body,
  })
  console.log(data);

  //GET returns the game, PATCH & POST return success or fail.
  return data;
}