"use client"
import { createClient } from '@/lib/supabase/client'

interface RequestBody {
  table: string,
  id?: number,
  action?: "RESET" | string,
  key?:string
}

export async function callSupabase(functionMethod:"GET"|"PATCH"|"POST", tableName:string, gameId?:number, gameAction?:string, playKey?:string){
  //Pull user's current JWT.
  const { data: { session } } = await createClient().auth.getSession();
  const jwt = session?.access_token;
  //Note that GameIDs are auto-generated by the edge function when using POST.
  const body: RequestBody = {
    table: tableName,
    id:gameId,
    action:gameAction,
    key:playKey,
  }

  let returnData:string = "", returnError:string = "";
  //GET methods can't have bodies, and that's a pain in the butt atm.
  if(functionMethod == "GET"){
    const { data, error} = await createClient().functions.invoke('postgres-edge', {
      method: 'PATCH',
      headers: {
        'Authorization': `Bearer ${jwt}`,
      },
      body,
    })
    returnData = data.returnBody;
    returnError = error;
  }
  else{
    //Invoke edge function with user's JWT.
    const { data, error } = await createClient().functions.invoke('postgres-edge', {
      method: `${functionMethod}`,
      headers: {
        'Authorization': `Bearer ${jwt}`,
      },
      body,
    })
    if(data == null){
      console.log("NON-GET returned null: "+returnError);
      return returnError;
    }
    returnData = data.returnBody;
    returnError = error;
  }
  console.log(returnData);
  if(returnData==null){
    console.log("Error in supabaseEdgeCaller: "+returnError);
    return returnError;
  }
  //GET returns the game, PATCH & POST return success or fail.
  return returnData;
}