"use client"
import { createClient } from '@/lib/supabase/client'

//To-do: assign player IDs to in-game "who's turn" array.
//Increment "Who's turn" counter on null player ID or turn submitted.
//Check all turn submitors against player ID in the [counter] array slot

//TicTacToe Actions: RESET | MOVE <Pos>
//ConnectFour Actions: RESET | MOVE <Col>

interface RequestBody {
  table: string,
  id?: number,
  action?: "RESET" | string,
  key?:string
}

interface PostReturn {
  id:number
  key:string
}
interface GetReturn{
  gameRow:any
}
interface combinedReturn{
  data?: PostReturn | GetReturn
  error?:string
}

const postgresEdge = 'postgres-edge';

export async function callSupabase(functionMethod:"GET"|"PATCH"|"POST"|"PlayerTracking", tableName:string, gameId?:number, gameAction?:string, playKey?:string):Promise<combinedReturn>{
  //Pull user's current JWT.
  const { data: { session } } = await createClient().auth.getSession();
  const jwt = session?.access_token;
  //Note that GameIDs are auto-generated by the edge function when using POST.
  const body: RequestBody = {
    table: tableName,
    id:gameId,
    action:gameAction,
    key:playKey,
  }
  const funcReturn:combinedReturn={};
  if(functionMethod == "PlayerTracking"){
    const { data, error} = await createClient().functions.invoke('postgres-players', {
      method: 'PATCH',
      headers: {
        'Authorization': `Bearer ${jwt}`,
      },
      body,
    })
    if(data){
      funcReturn.data = data.returnBody;
    }
    funcReturn.error = error;
  }
  //GET methods can't have bodies, and that's a pain in the butt atm.
  else if(functionMethod == "GET"){
    const { data, error} = await createClient().functions.invoke(postgresEdge, {
      method: 'PATCH',
      headers: {
        'Authorization': `Bearer ${jwt}`,
      },
      body,
    })
    if(data){
      funcReturn.data = data.returnBody;
    }
    funcReturn.error = error;
  }
  else{
    //Invoke edge function with user's JWT.
    const { data, error } = await createClient().functions.invoke(postgresEdge, {
      method: `${functionMethod}`,
      headers: {
        'Authorization': `Bearer ${jwt}`,
      },
      body,
    })
    if(data){
      funcReturn.data = data.returnBody;
    }
    funcReturn.error = error;
  }
  //console.log(funcReturn.data);
  if(funcReturn.data==null){
    console.log("Error in supabaseEdgeCaller: "+funcReturn.error);
  }
  //GET returns the game, PATCH & POST return success or fail.
  return funcReturn
}